# This file was generated by GoReleaser. DO NOT EDIT.
class Gas < Formula
  desc "Check the state of all your git worktrees."
  homepage "https://4d63.com/gas"
  version "3.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leighmcculloch/gas/releases/download/v3.1.0/gas_3.1.0_darwin_amd64.tar.gz"
    sha256 "281dbb44956b85410423e51c89cfc484895858bd2f797f850c41236b4b5f32ea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/gas/releases/download/v3.1.0/gas_3.1.0_linux_amd64.tar.gz"
      sha256 "8399ec4b5ce26d40fa307f6116e7f2ea0e4739969ef19534198e1bdce46fbf38"
    end
  end

  def install
    bin.install "gas"
  end

  test do
    system "#{bin}/gas -help"
  end
end
