# This file was generated by GoReleaser. DO NOT EDIT.
class Gas < Formula
  desc "Check the state of all your git worktrees."
  homepage "https://4d63.com/gas"
  version "3.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leighmcculloch/gas/releases/download/v3.0.2/gas_3.0.2_darwin_amd64.tar.gz"
    sha256 "04b5c9dbb1dae4bed7d1263de013fde9c305e11a4465ee328784657ceb2fa393"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/gas/releases/download/v3.0.2/gas_3.0.2_linux_amd64.tar.gz"
      sha256 "8ecb3d6a9b1cdae8bef12475b85ed85b72fbed8ede0c3a4fe4fbd4b103e8ea3f"
    end
  end

  def install
    bin.install "gas"
  end

  test do
    system "#{bin}/gas -help"
  end
end
