# This file was generated by GoReleaser. DO NOT EDIT.
class Gas < Formula
  desc "Check the state of all your git worktrees."
  homepage "https://github.com/leighmcculloch/gas"
  version "3.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leighmcculloch/gas/releases/download/v3.1.1/gas_3.1.1_darwin_amd64.tar.gz"
    sha256 "a7f459253da3afeca163b80b8fcf0a1351bd275947ae50028c1c6b585dc1ac02"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/gas/releases/download/v3.1.1/gas_3.1.1_linux_amd64.tar.gz"
      sha256 "f312e2b8f71ce5b786c4ceda8f164f20cb891161639782518ae057a014813b6b"
    end
  end

  def install
    bin.install "gas"
  end

  test do
    system "#{bin}/gas -help"
  end
end
